name-template: 'v$COMPLETE'
tag-template: 'v$COMPLETE'

categories:
  - title: 'Features'
    label: 'feat'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Pipeline'
    label: 'ci'
  - title: 'Maintenance'
    label: 'chore'

template: |
  $CHANGES