package io.github.bcaillard.jspecifyutilities.packageinfogenerator.integrationtest.PackageInfoMainJavaAndTestJavaGeneratorMojoIT.generate_from_main_and_test_sources_directories_test_case.src.main.java.com.acme.app.subpackage.hadpackageinfo.foo;

public class Empty {

}